### ISSUE TITLE
Cloud Run Build Error

### ISSUE THREAD

**Issue by theobouwman** [GoogleCloudPlatform/cloud-profiler-python#141]
I am running on FastAPI but get a build error on Cloud Run:

```
Step #0 - "Build": Failed to build google-cloud-profiler
Step #0 - "Build": ERROR: Could not build wheels for google-cloud-profiler, which is required to install pyproject.toml-based projects
```

Base Dockerfile:
```
FROM tiangolo/uvicorn-gunicorn:python3.11-slim
```

**Comment by krstef** [comment]
According to instructions in [README](https://github.com/GoogleCloudPlatform/cloud-profiler-python/blob/main/README.md#installation-on-linux-alpine), it is required to install `build-base` package as part of Alpine image in order to be able to build `cloud-profiler-python` properly.

Since you're using `python3.11-slim` as a base image, you should install equivalent package to `build-base`, which is in your case `build-essential`.
You can install required package as follows:
`RUN apt-get update && apt-get install -y --no-install-recommends build-essential`

**Comment by aabmass** [comment]
@krstef's answer is correct. Please re-open if that doesn't solve the issue for you
