### ISSUE TITLE
Error when used with google-cloud-pubsub==1.5.0

### ISSUE THREAD

**Issue by NicholasAzar** [GoogleCloudPlatform/cloud-profiler-python#66]
When deploying a app engine flex app with the google-cloud-pubsub==1.5.0, the following error is seen in the logs:

```
INFO:googlecloudprofiler:Google Cloud Profiler Python agent version: 2.0.4
DEBUG:googlecloudprofiler.client:Profiler has started
ERROR:googlecloudprofiler.client:Failed to build the Discovery client for profiler (will retry after 40.744s): 'ClientOptions' object has no attribute 'credentials_file'
```

This is only fixed when google-cloud-pubsub is upgraded to 1.6.0 or greater.

**Comment by kalyanac** [comment]
Thank you for reporting this. I did not chase this down fully, but here are my observations.

When I tried to install pubsub 1.5.0 and latest version of profiler using `pip`, it complains about incompatibility in dependencies, specifically google-api-core and google-api-python-client. 

Since pip issues warnings during install and there is a valid workaround, I will close this issue. 

Please reopen if you have any further questions on this.
